### ISSUE TITLE
Add test case for cube sphere

### ISSUE THREAD

**Issue by raphaeldussin** [MITgcm/xmitgcm#111]
We need to add a test case for cube sphere (to support #98).

This would add a 5M archive to the test suite. Is it the right way to go
or should we move large files to git-lfs ? this would reduces greatly the size
of the project but it also comes with limitations : 

https://help.github.com/articles/about-storage-and-bandwidth-usage/

**Comment by rabernat** [comment]
I agree we need a better way to manage file downloads for test. I don't like git LFS. I had problems with it. We actually used to use it but I removed it!

I think the test data should live in a standalone repository or perhaps some place like figshare / zenodo. Then we should have a module which downloads and caches it as part of the test process.

I recommend emailing the xarray mailing list to find out what other people are doing. I think a lot of data-driven packages have this same problem, and I'm sure someone has come up with an elegant solution.

**Comment by raphaeldussin** [comment]
I uploaded test data on figshare, closing this issue
