### ISSUE TITLE
Add parallel option to open_mdsdataset

### ISSUE THREAD

**Issue by malmans2** [MITgcm/xmitgcm#148]
I think it would be helpful to have the option `parallel` in open_mdsdataset.
I have a dataset with 20k files and this is what I get:

```python
from dask.distributed import Client
import xmitgcm
client = Client(threads_per_worker=1)
print(client)
path = '/home/idies/workspace/OceanCirculation/fromNeil'
for p in [True, False]:
    print('\nparallel={}'.format(p))
    %time xmitgcm.open_mdsdataset(data_dir=path, ignore_unknown_vars=True, parallel=p)
```

    <Client: scheduler='tcp://127.0.0.1:33596' processes=16 cores=16>
    
    parallel=True
    CPU times: user 1min 18s, sys: 17 s, total: 1min 35s
    Wall time: 1min 35s
    
    parallel=False
    CPU times: user 5min 8s, sys: 1min 15s, total: 6min 24s
    Wall time: 5min 48s

I also like a lot being able to see what's going on with the dask dashboard.
All I did is changing this:
https://github.com/xgcm/xmitgcm/blob/310f3c82699f458e24beb1313702a1acf5eda2af/xmitgcm/mds_store.py#L204-L206
with this:
```python
                # wrap the open_mdsdataset with delayed
                if parallel:
                    import dask
                    open_ = dask.delayed(open_mdsdataset)
                else:
                    open_ = open_mdsdataset

                datasets = [open_(data_dir,
                                  iters=iternum,
                                  read_grid=False,
                                  **kwargs) for iternum in iters]
                if parallel:
                    # calling compute here will return the datasets lists,
                    # the underlying datasets will still be stored as dask arrays
                    datasets = dask.compute(datasets)[0]
```
Should I submit a PR?

**Comment by rabernat** [comment]
Hi @malmans2 - thanks for raising this important issue. I agree we really need to speed up the the dataset creation process.

When I have profiled this in the past, I found that nearly all of the time was being spent calling `glob`. I think there are some very simple optimizations we could do that would greatly speed things up. I have been meaning to work on this, and I'm glad you reminded me about it.

I'm curious what exactly is being parallelized in your example above?

**Comment by malmans2** [comment]
I explored the code a little more and indeed I noticed that glob is used in functions that are called in for loops.
For example, in my case (~20k files) about 30s are spent in this checking part:
https://github.com/xgcm/xmitgcm/blob/5eba013b90ddd00a2b674bd1fa5bb1d47336eb5c/xmitgcm/mds_store.py#L174-L181

Have you considered using glob just once at the very beginning, then create a pandas dataframe? Here is an example (same piece of code mentioned above), where the time spent in the for loop drops from ~30s to less than ~2s.

```python
# Import
from glob import glob
import os
import pandas as pd

# data dir
data_dir = '/home/idies/workspace/OceanCirculation/fromNeil'
```


```python
# From xmitgcm
def _get_all_iternums(data_dir, file_format='*.??????????.data'):
    """Scan a directory for all iteration number suffixes."""
    iternums = set()
    all_datafiles = glob(os.path.join(data_dir, file_format))
    istart = file_format.find('?')-len(file_format)
    iend = file_format.rfind('?')-len(file_format)+1
    for f in all_datafiles:
        iternum = int(f[istart:iend])
        prefix = os.path.split(f[:istart-1])[-1]
        iternums.add(iternum)
    iterlist = sorted(iternums)
    return iterlist

def _get_all_matching_prefixes(data_dir, iternum):
    """Scan a directory and return all file prefixes matching a certain
    iteration number."""
    if iternum is None:
        return []
    prefixes = set()
    all_datafiles = glob(os.path.join(data_dir, '*.%010d.data' % iternum))
    for f in all_datafiles:
        iternum = int(f[-15:-5])
        prefix = os.path.split(f[:-16])[-1]
        prefixes.add(prefix)
    return list(prefixes)
```


```python
%%time
xmitgcm_prefixes = []
for iternum in _get_all_iternums(data_dir):
    xmitgcm_prefixes += [_get_all_matching_prefixes(data_dir, iternum)]
```

    CPU times: user 28.4 s, sys: 2.42 s, total: 30.9 s
    Wall time: 30.9 s



```python
# Use pandas
def create_dataframe(data_dir):
    filenames = glob(os.path.join(data_dir, '*'))
    d = {'prefix': [], 'iternum': [], 'suffix': [],
         'filename': []}
    for filename in filenames:
        name = filename.split('/')[-1]
        splitted = name.split('.')
        # Check that is prefix.iternum.data or prefix.iternum.meta
        if (len(splitted) != 3
             or not splitted[1].isdigit()
             or not splitted[2] in ['data', 'meta']):
            continue
        d['prefix'] += [splitted[0]]
        d['iternum'] += [int(splitted[1])]
        d['suffix'] += [splitted[2]]
        d['filename'] += [filename]
    return pd.DataFrame(d)
```


```python
%%time
df = create_dataframe(data_dir)
my_prefixes = []
df_data = df[df['suffix'] == 'data']
for i in pd.unique(df['iternum']):
    my_prefixes += [df_data[df_data['iternum'] == i]['prefix'].to_list()]
```

    CPU times: user 1.33 s, sys: 36.1 ms, total: 1.36 s
    Wall time: 1.35 s



```python
for _, (x, m) in enumerate(zip(xmitgcm_prefixes, my_prefixes)):
    assert set(x) == set(m)
```

**Comment by rabernat** [comment]
@malmans2 - I would be happy if you would start a PR to implement this idea.

I would prefer not to use pandas internally if we can avoid it. I think the simplest approach is to
- use [os.listdir](https://docs.python.org/3/library/os.html#os.listdir) to build a cache of the data_dir and grid_dir contents (list a list)
- use [fnmatch](https://docs.python.org/3.4/library/fnmatch.html) to replace the `*.meta`-style globbing.

I think this would minimize the amount of code that needs to be changed.

**Comment by malmans2** [comment]
It should be an easy fix. From `pytest` docs:
For example:
```
with pytest.raises(TimeoutError, message="Client got unexpected message"):
    wait_for(websocket.recv(), 0.5)
```

Becomes:
```
with pytest.raises(TimeoutError):
    wait_for(websocket.recv(), 0.5)
    pytest.fail("Client got unexpected message")
```

**Comment by avik2007** [comment]
Hi there,

I'm wondering, did this suggestion get implemented?
