### ISSUE TITLE
metric_vector_pairs not working for second of vector pair

### ISSUE THREAD

**Issue by cspencerjones** [MITgcm/xmitgcm#154]
In llcreader, the second of the metric vector pair is still assigned a negative value in some of the domain (even though metric vector pairs should not change sign when they pass through llcreader). I think this is because "metric" is not passed to transform_u_to_v. 

I'll try to fix it myself but wanted to raise an issue for completeness.

**Comment by rabernat** [comment]
@cspencerjones - I'm trying to catch up on xmitgcm issues. Was this fixed?

**Comment by cspencerjones** [comment]
yes!
