### ISSUE TITLE
vertical grid information on llcreader

### ISSUE THREAD

**Issue by ocesaulo** [MITgcm/xmitgcm#166]
Hello,

Seems that the vertical grid (Z, Zl,Zu) is missing (horizontal too) for LLC4320 data read through llcreader from the ECCO portal using the ECCO4320 class; maybe that is because of design (custom make_coord function), or maybe that was because the vertical info was not there at the source since it seems that xmitgcm has the machinery do it (from the ../variables import I see the coordinates variables are loaded), such that grid information is meant to be read from somewhere else. 

While I can't find where to read the vertical grid elsewhere, I can find the horizontal grid in a pangeo catalog, but that is for surface only so no Z info.

It would be nice if llcreader could read the full grid. I can help if pointed to the relevant parts of the code if that is something. If not can someone point me where to find the vertical grid?

**Comment by dhruvbalwada** [comment]
The grid that @rabernat has shared on the pangeo server does not have the Z coordinate in it. It seems to only be a grid for the surface as the Z is a single number with the surface value.

**Comment by Mikejmnez** [comment]
Hi,

In addition to having vertical (Z) grid terms available, it would also be very useful to have the terms (XU,YU) and (XV, YV) as well (and even metrics terms dXV, dYU). Some of these can be calculated somewhat easily when face is not a dimension, but it is much more involved in the presence of complex grid topology.

cheers, 
Miguel

**Comment by rabernat** [comment]
> it would also be very useful to have the terms (XU,YU) and (XV, YV) as well (and even metrics terms dXV, dYU).

Those terms were not output. Here is the full list of grid variables.

```
AngleCS.data
AngleSN.data
Depth.data
DRC.data
DRF.data
DXC.data
DXG.data
DYC.data
DYG.data
hFacC.data
hFacS.data
hFacW.data
PHrefC.data
PHrefF.data
RAC.data
RAS.data
RAW.data
RAZ.data
RC.data
RF.data
RhoRef.data
U2zonDir.data
V2zonDir.data
XC.data
XG.data
YC.data
YG.data
```
