### ISSUE TITLE
print in open_mdsdataset creates annoying jupyter notebook cell output

### ISSUE THREAD

**Issue by cspencerjones** [MITgcm/xmitgcm#182]
Not urgent at all, but the new `print(ds.time.encoding)` statement in `open_mdsdataset` creates a lot of printed output if you load in many timesteps. This is annoying. Can we just output the first one?

**Comment by rabernat** [comment]
This is a total bug, something we added for debugging that should have been removed before merging.

Could you make a PR to remove it?
