### ISSUE TITLE
Problems loading LLC90 data

### ISSUE THREAD

**Issue by emmomp** [MITgcm/xmitgcm#184]
I'm having a go at loading some LLC90 data generated from ECCOv4. I have a fresh install of xmitgcm via a github clone. Following the documentation, I'm first creating the extra metadata via:

```
llc90_extra_metadata = xmitgcm.utils.get_extra_metadata(domain='llc', nx=90)
```

 then trying to load a datafile using:

```
xmitgcm.open_mdsdataset(data_dir=rootdir+expdir,grid_dir=rootdir+griddir,prefix=[VARNAME],extra_metadata=llc90_extra_metadata)
```
And I'm getting the error:

>  TypeError                                 Traceback (most recent call last)
> 
> <ipython-input-21-f2804570e5b4> in <module>()
> ----> 1 xmitgcm.open_mdsdataset(data_dir=rootdir+expdir,grid_dir=rootdir+griddir,prefix=['adxx_qnet'],extra_metadata=llc90_extra_metadata)
> 
> ~/Python/xmitgcm/xmitgcm/mds_store.py in open_mdsdataset(data_dir, grid_dir, iters, prefix, read_grid, delta_t, ref_date, calendar, levels, geometry, grid_vars_to_coords, swap_dims, endian, chunks, ignore_unknown_vars, default_dtype, nx, ny, nz, llc_method, extra_metadata)
>     247                           default_dtype=default_dtype,
>     248                           nx=nx, ny=ny, nz=nz, llc_method=llc_method,
> --> 249                           levels=levels, extra_metadata=extra_metadata)
>     250     ds = xr.Dataset.load_store(store)
>     251 
> 
> ~/Python/xmitgcm/xmitgcm/mds_store.py in __init__(self, data_dir, grid_dir, iternum, delta_t, read_grid, file_prefixes, ref_date, calendar, geometry, endian, ignore_unknown_vars, default_dtype, nx, ny, nz, llc_method, levels, extra_metadata)
>     424 
>     425         if has_faces:
> --> 426             nyraw = self.nx*self.nface
>     427         else:
>     428             nyraw = self.ny
> 
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

Which looks like an error when trying to initialise the grid. Any help would be appreciated!
Thanks

**Comment by rabernat** [comment]
Hi Emma! 

I would try without the `extra_metadata` part. Follow these instructions instead:
https://xmitgcm.readthedocs.io/en/latest/usage.html#grid-geometries
```python
ds = open_mdsdataset(data_dir=rootdir+expdir,
                     grid_dir=rootdir+griddir,
                     prefix=[VARNAME],
                     geometry='llc')
```

I agree that the documentation is confusing and ambiguous, suggesting two different ways to accomplish the same things. Hopefully @raphaeldussin can give some thought to this and figure out how to resolve it.

**Comment by raphaeldussin** [comment]
@emmomp I think if you add nx=90 to the open_mdsdataset it should work.

```python

xmitgcm.open_mdsdataset(data_dir=rootdir+expdir,
                                            grid_dir=rootdir+griddir,
                                            prefix=[VARNAME],
                                            nx=90,
                                            extra_metadata=llc90_extra_metadata)

```

The nx value is contained in the extra_metadata and I would like not to have to pass it but I couldn't get the different conditionals in mds datastore to work properly without an explicit nx value.

**Comment by rabernat** [comment]
@raphaeldussin - I believe we are giving Emma conflicting advice here.

open_mdsdataset should work *without `extra_metadata`* and *without specifying `nx`*. This is how all out standard test cases work, and what the original documentation recommends (https://xmitgcm.readthedocs.io/en/latest/usage.html#grid-geometries). We should try to keep things as simple as possible for users. I feel that the `extra_metadata` option should be discouraged unless absolutely necessary for a weird configuration, like ASTE.

I don't believe there is anything about Emma's case that should require such special options. @emmomp -- could you check whether my suggestion above worked?

In the long run, we need to update the documentation to be more clear on these points.

**Comment by emmomp** [comment]
Both methods work, thanks guys!
