### ISSUE TITLE
xarray 0.14.1 error using 'auto_combine'

### ISSUE THREAD

**Issue by emmomp** [MITgcm/xmitgcm#186]
Using xarray version 0.14.1 I get the following warning on calling xmitgcm.open_mdsdataset. It also fails to read the llc file correctly and the output data is only size dask.array<chunksize=(1, 1, 1, 90, 90>). When I use xarray 0.10 I get dask.array<shape=(208, 50, 13, 90, 90), chunksize=(1, 1, 1, 90, 90)>

> /data/smurphs/miniconda3/lib/python3.7/site-packages/xmitgcm/mds_store.py:217: FutureWarning: In xarray version 0.15 `auto_combine` will be deprecated. See
> http://xarray.pydata.org/en/stable/combining.html#combining-multi
>   ds = xr.auto_combine(datasets)
> /data/smurphs/miniconda3/lib/python3.7/site-packages/xmitgcm/mds_store.py:217: FutureWarning: The datasets supplied have global dimension coordinates. You may want
> to use the new `combine_by_coords` function (or the
> `combine='by_coords'` option to `open_mfdataset`) to order the datasets
> before concatenation. Alternatively, to continue concatenating based
> on the order the datasets are supplied in future, please use the new
> `combine_nested` function (or the `combine='nested'` option to
> open_mfdataset).The datasets supplied require both concatenation and merging. From
> xarray version 0.15 this will operation will require either using the
> new `combine_nested` function (or the `combine='nested'` option to
> open_mfdataset), with a nested list structure such that you can combine
> along the dimensions None. Alternatively if your datasets have global
> dimension coordinates then you can use the new `combine_by_coords`
> function.
>   ds = xr.auto_combine(datasets)

**Comment by emmomp** [comment]
Simply replacing 'auto_combine' with 'combine_by_coords' as suggested does not seem to work. I've downgraded to xarray 0.12.0 and it's working fine again

**Comment by rabernat** [comment]
Hi @emmomp - thanks for reporting this! We really appreciate it. Will try to fix asap.

**Comment by rabernat** [comment]
So I just re-ran our test suite to make sure to double check we were testing against xarray 0.14.1 (we are):
https://travis-ci.org/MITgcm/xmitgcm/jobs/615752101

All of the tests passed, including the ones involving llc90. So it looks like you have a situation that is not covered by the tests. Could you please provide _as much information as possible_ about what you are doing that triggered this error? Just copy and past the full command you are using, plus the entire stack trace from the error. Thanks!

**Comment by emmomp** [comment]
My bad, I was confused by the xarray preview of the dataset as it no longer shows the shape of data variables and it looked like it was only one chunk large. It is in fact working, my apologies!
