### ISSUE TITLE
can't plot or transform llc4320 data to netcdf

### ISSUE THREAD

**Issue by lanmanli** [MITgcm/xmitgcm#188]
I am trying to plot ssh at a some point,but get some error.

This is what i wrote:
from xmitgcm import llcreader
model = llcreader.ECCOPortalLLC4320Model()
ds = model.get_dataset(varnames=['Eta'])
a1=ds['Eta'].sel(face=4,time=slice("2011-09-15T05:00:00","2011-09-15T05:00:00"))
a1=a1.mean(dim='time')
a1.plot()

The error is:
TypeError: request() got an unexpected keyword argument 'size_policy'

**Comment by rabernat** [comment]
HI @lanmanli - thanks for your question.

This is the same issue as #175. You need to update xmitgcm and fsspec to their latest versions. Please see #175 for detailed instructions on how to resolve.

**Comment by lanmanli** [comment]
Thank you very much for your reply. I'm very sorry, but I may have to hold you up a bit.
 I have update xmitgcm and fsspec with conda,now their version is 0.4.1 and 0.6.0 respectively.And I also edited to remove unnecessary NUMPY_EXPERIMENTAL_ARRAY_FUNCTION stuff.  But still get the same error.

Here is my code:

import os
os.environ['NUMPY_EXPERIMENTAL_ARRAY_FUNCTION']='0'
import xmitgcm
from xmitgcm import llcreader
import fsspec
print(xmitgcm.__version__, fsspec.__version__)
model = llcreader.ECCOPortalLLC4320Model()
ds = model.get_dataset(varnames=['Eta'])
a1=ds['Eta'].sel(face=4,time=slice("2011-09-15T05:00:00","2011-09-15T05:00:00"))
a1=a1.mean(dim='time')
a1.plot()


TypeError: request() got an unexpected keyword argument 'size_policy'
