### ISSUE TITLE
ECCOPortalLLC4320Model max date is 2012-09-23 instead of 2012-11-15

### ISSUE THREAD

**Issue by antonimmo** [MITgcm/xmitgcm#193]
As far as I know, LLC4320 output spans from 13 September 2011 to 15 November 2012, but ECCOPortalLLC4320Model last datetime is 2012-09-23T05:00:00, so there are almost 2 months of data missing.

Does this have to do with the ECCO portal itself, or llcreader implementation?

I've dug a bit into the ECCO portal and realised that while regional data (e.g. [CalCoast/U](https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_4320/regions/CalCoast/U&next=9)) has hourly outputs from 2011-09-13T01:00:00 to 2012-09-21T23:00:00, compressed data gets up to [iter 1450224](https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_4320/compressed/0001450224) which, if 144 iterations equals 1 hour, then 1450224/144/24 = 419.625 days, so dates would range from 2011-09-13 to 2012-11-05. 

This last number is bigger than the 9030/24 = 376.25 days that ECCOPortalLLC4320Model().get_dataset() offers.

So, am I missing something? More importantly, is there a way to get september-octuber/2012 data?

Thanks.

**Comment by antonimmo** [comment]
Just pinging on this one. Meanwhile, I will have to consider July-August-September as summer instead of August-September-October.

**Comment by rabernat** [comment]
You should be able to override the `iter_stop` by specifying it when you call get_dataset, i.e.

```python
from xmitgcm import llcreader
model = llcreader.known_models.ECCOPortalLLC4320Model()
ds = model.get_dataset(varnames=['Eta'], iter_stop=1450224)
```

or override it for the model object
```python
model.iter_stop = 1450224
```

If you can confirm that these data actually exist, we would welcome a pull-request to change the defaults:
https://github.com/MITgcm/xmitgcm/blob/1fb9cc2520d0df1cf199b347d94c91853d22dddb/xmitgcm/llcreader/known_models.py#L44-L50

**Comment by antonimmo** [comment]
I tried different values for `iter_stop`, and `1495152` seems to be the very last one.

That iteration corresponds to `2012-11-15T14:00:00`, which also agrees with what I was told. 

I'll do the pull request asap.

Thanks.

**Comment by antonimmo** [comment]
Done. Sorry for the delay. I created #203
