### ISSUE TITLE
llcreader is helpful for a new study

### ISSUE THREAD

**Issue by hongandyan** [MITgcm/xmitgcm#201]
Hello xmitgcm developers,
want to report that xmitgcm is useful for this study
The Seasonality of Submesoscale Energy Production, Content, and Cascade
https://doi.org/10.1029/2020GL087388
where xmitgcm is explicitly acknowledged:
"The LLC4320 data can be directly accessed from ECCO Data Portal (https://data.nas.nasa.gov/ecco/data.php), or more conveniently downloaded by using the xmitgcm python package (https://xmitgcm.readthedocs.io/en/latest/index.html). "
thanks for your hard work.

**Comment by rabernat** [comment]
Thank you so much for sharing this. It means a lot to see these tools used for exciting new science!

Please consider reporting your publication here:
https://forms.gle/HNEBk8e19EWP4Uo2A

It will help us maintain funding for this sort of work.

**Comment by hongandyan** [comment]
done. can't find "xmitgcm" so "xarray" is picked. Hope it's right.
