### ISSUE TITLE
Assertion errors when using LLC4320 model

### ISSUE THREAD

**Issue by loisbaker** [MITgcm/xmitgcm#202]
Hi, I've been working with the LLC4320 dataset on ocean.pangeo.io, which has been working really well. Today, I am getting assertion errors whenever data needs to be loaded - so whenever I try .load() , .values , .plot() etc. Does anyone have any idea why this has started happening? The error can be recreated with:

`import xmitgcm.llcreader as llcreader`
`import numpy as np`
`model = llcreader.ECCOPortalLLC4320Model()`
`s = model.get_dataset(varnames=['U','V'],k_levels = [1], iter_start=283392, iter_step =1, iter_stop=283392+1)`
`temp = s.U.values`

The error message is very long, but here's the beginning and the end:

<img width="830" alt="Screenshot 2020-05-22 at 12 56 06" src="https://user-images.githubusercontent.com/43139023/82665584-01264200-9c2c-11ea-9e9c-6f49aa331fc0.png">

<img width="1016" alt="Screenshot 2020-05-22 at 12 56 17" src="https://user-images.githubusercontent.com/43139023/82665575-fcfa2480-9c2b-11ea-8077-121b4b03cc15.png">

Any help would be great! 
Thanks,
Lois

**Comment by rabernat** [comment]
Hi Lois! Thanks for reporting this error. It's really helpful to have user feedback.

It looks like the ECCO data portal is down!
https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_4320/compressed/0000283392

![image](https://user-images.githubusercontent.com/1197350/82668170-33717880-9c07-11ea-90be-5f827483f963.png)

The error is telling you that the data that was downloaded (probably zero) is not the expected size. It would be nice if we had a more informative error message here.

The website says to report to support@nas.nasa.gov If the problem persists for more than 30 minutes, . Would you be willing to make a report? You don't have to include the details of xmitgcm--just state that the files all say "data temporarily unavailable."

**Comment by loisbaker** [comment]
Thanks for getting back so quickly Ryan, it makes sense that this would be the problem! I'll report it now as you say.

**Comment by loisbaker** [comment]
The ECCO portal is up again now, and my code is running properly again. Thanks!
