### ISSUE TITLE
Accessing LLC4320 on Pleiades

### ISSUE THREAD

**Issue by jbrasch** [MITgcm/xmitgcm#206]
When creating an instance of the PleiadesLLC4320Model class in llcreader, `mask_path` is set to `'/nobackup/rpaberna/llc/masks/llc_4320_masks.zarr'` by default. I don't have access to the `/nobackup/rpaberna/` directory. Is there some process for obtaining access, another place `llc_4320_masks.zarr` is located, or a way for me to generate this zarr myself?

**Comment by rabernat** [comment]
Sorry about that @jbrasch. I am looking into this. There must be a permissions problem.

**Comment by jbrasch** [comment]
Thank you for your help with this, @rabernat ! Do you know how long it usually takes to resolve problems like this?

**Comment by rabernat** [comment]
It should be quick in principle, but my NAS account had been suspended because I had forgotten to take the security training. Just too many things on my todo list. I hope to have it resolved by the end of the day. Thanks for your patience.

**Comment by rabernat** [comment]
Hi @jbrasch -- sorry for the delay. I tried playing around with the permissions. Can you try again?

**Comment by jbrasch** [comment]
Everything is working, I appreciate it.
