### ISSUE TITLE
multilple fields in one output stream

### ISSUE THREAD

**Issue by hongandyan** [MITgcm/xmitgcm#219]
Does "open_mdsdataset" can read multiple fields stored in one output stream, 
for example, to read "ETAN" from "state_2d_set1.*.data" generated by
https://github.com/ECCO-GROUP/ECCO-v4-Configurations/blob/master/ECCOv4%20Release%203/namelist/data.diagnostics#L17
to
https://github.com/ECCO-GROUP/ECCO-v4-Configurations/blob/master/ECCOv4%20Release%203/namelist/data.diagnostics#L28
thanks!

**Comment by timothyas** [comment]
Hey @hongandyan, if I understand correctly I think this is xmitgcm's bread and butter. You can get 'ETAN' many ways. Most simply by pointing xmitgcm's `data_dir` to the diags/ directory it will read all mds files, and get all the fields within each file at all time steps. Or you can add the `prefix`=`state_2d_set1` to only read files with that prefix (see [here](https://xmitgcm.readthedocs.io/en/latest/usage.html) for options). An example for reading the ECCO (llc90) is as follows: 

```
ds = open_mdsdataset(data_dir='/path/to/diags', grid_dir='/optional/path/to/grid/files/if/separate',delta_t=3600, ref_date='1992-01-1',geometry='llc')
ds['ETAN']
```
(the geometry option is all that is completely necessary, but `ref_date` and `delta_t` makes the time work out well).
You could also use ecco_v4_py's function [load_ecco_vars_from_mds](https://github.com/ECCO-GROUP/ECCOv4-py/blob/e8dc991facb4a33829ecdf5ecbb1b4b7767f393f/ecco_v4_py/read_bin_llc.py#L31) which was meant to be a simple wrapper for open_mdsdataset with these ECCO options, but it has become quite bloated with other things. 

I hope that helps, let me know!

**Comment by hongandyan** [comment]
thanks @timothyas ! You answer exactly what I want.
