### ISSUE TITLE
 Report error“request() got an unexpected keyword argument 'size_policy"

### ISSUE THREAD

**Issue by csy0101** [MITgcm/xmitgcm#222]
"model = llcreader.ECCOPortalLLC4320Model()
ds = model.get_dataset(varnames=['U','V'], k_levels=[0],k_chunksize = 90,iter_start=13680, iter_stop=13824, iter_step=144,type='faces')
ds
unorm = colors.DivergingNorm(vmin=-2, vcenter=0, vmax=2)
plt.figure(figsize=(12,10))
ds.U.isel(k=0,face=5,time=0).plot(norm=unorm)
plt.show()"
TypeError: request() got an unexpected keyword argument 'size_policy'
I have viewed #175, xmitgcm 0.4.1   fsspec  0.8.2  still report error

**Comment by rabernat** [comment]
We need to make a new release of xmitgcm. In the meantime, please make sure you're running the latest version from github:

```
pip install git+https://github.com/MITgcm/xmitgcm.git
```

**Comment by rabernat** [comment]
Now that 0.5.0 is released, this should be fixed.
