### ISSUE TITLE
where and how to download the *.meta and *.data files?

### ISSUE THREAD

**Issue by Shihong-Wang** [MITgcm/xmitgcm#228]
The data on ECCO data portal is *.shrunk. So where we can download the *.meta an *.data files directly?
We also have tried to download the llc4320 data by xmitgcm, but the following error showed up when we tried to plot or save to nc files:
TypeError: request() got an unexpected keyword argument 'size_policy'
Sometimes the same program will report this error:
KeyError: 'https://storage.googleapis.com/pangeo-ecco/llc/masks/llc_4320_masks.zarr/.zmetadata'
I checked the versions of xmitgcm and fsspec as this issue discussed: https://github.com/MITgcm/xmitgcm/issues/175, they are 0.4.1 and 0.8.2.
so can you enlighten me to solve thisproblem?

this is my code:
import os
os.environ['NUMPY_EXPERIMENTAL_ARRAY_FUNCTION']='0'
import xmitgcm
from xmitgcm import llcreader
import fsspec
import matplotlib.pyplot as plt

model = llcreader.ECCOPortalLLC4320Model()
#print(model)
#print(model.varnames)
#ds = model.get_dataset(varnames=['Eta'],k_chunksize=90,iter_start=0, iter_stop=9, iter_step=8)
ds = model.get_dataset(varnames=['Eta'],k_chunksize=90,iter_start=0, iter_stop=9)
print(ds)
sel_ds = ds.isel(time=0,face=5) 
sel_ds.time.values
print(sel_ds)

#plt.figure(figsize=(12,10))
#sel_ds.Eta.plot()
#plt.show()
sel_ds.to_netcdf('my_file.nc')

**Comment by dhruvbalwada** [comment]
The inconsistent behavior is being discussed here #210

**Comment by shu-duo** [comment]
so,how do you slove your problem? I met the same question, and i really want to know how to download .data files. Thanks in advance.

**Comment by dhruvbalwada** [comment]
Maybe the discussion in this issue: https://github.com/MITgcm/xmitgcm/issues/175 can help?

**Comment by shu-duo** [comment]
Mr. Balwada,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; thank you for your reply! It is helpful.&nbsp;However, I now have a new issue. I have downloaded the .data.shrunk files to my computer, and I am wondering how I can unzip them and read the data. I have read #275, and my code is as the first attachment, but I am encountering the error list the second attachment, what can i do to fulfill my goal?&nbsp; how to get grid_path? Thanks in advance.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; shu duo
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MITgcm/xmitgcm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月30日(星期一) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MITgcm/xmitgcm] where and how to download the *.meta and *.data files? (#228)





 
Maybe the discussion in this issue: #175 can help?
