### ISSUE TITLE
can't save to netcdf

### ISSUE THREAD

**Issue by LemingVan** [MITgcm/xmitgcm#232]
Hi, I'm new to python, maybe the question is very simple.

I build a binder in Github using Pangeo binder, which can handle the MITgcm LLC4320 huge dataset. When I use the "to_netcdf", only the 2D(i, j) data can be transferred, when the data include "k", like 2D(i, k) or 3D(i, j, k), it will stop at 83% each time. I'm not sure what happened, can anyone help me? [jupyter notebook address](https://github.com/LemingVan/Pangeo/blob/master/save_llc_data_V1.ipynb)

<img width="1072" alt="截屏2020-10-31 下午3 24 43" src="https://user-images.githubusercontent.com/46369483/97774024-86286680-1b8f-11eb-86fc-361fb44fe51c.png">
<img width="1075" alt="截屏2020-10-31 下午3 25 26" src="https://user-images.githubusercontent.com/46369483/97774025-888ac080-1b8f-11eb-9636-c74647e8e956.png">
<img width="1078" alt="截屏2020-10-31 下午3 25 48" src="https://user-images.githubusercontent.com/46369483/97774026-8aed1a80-1b8f-11eb-86fb-56c12b6bdf0c.png">
<img width="1074" alt="截屏2020-10-31 下午3 26 32" src="https://user-images.githubusercontent.com/46369483/97774027-8de80b00-1b8f-11eb-9a24-f42e1c41db43.png">

**Comment by rabernat** [comment]
Perhaps you are running out of memory? Does your session crash, or does it just hang here forever?

**Comment by LemingVan** [comment]
Hi @rabernat , I can download more than 1GB 2D(i, j) data, this one is really small to that.
The code will stop without any error massages, you can see that from the pic below (it will stop when the Python3 kernel out of work)
 
<img width="1436" alt="截屏2020-11-03 上午9 09 58" src="https://user-images.githubusercontent.com/46369483/97935967-1a274780-1db5-11eb-9861-f3a2c5a1d27f.png">

And you are welcome to reproduce this issue from [here](https://binder.pangeo.io/v2/gh/LemingVan/Pangeo.git/master).

**Comment by rabernat** [comment]
> I can download more than 1GB 2D(i, j) data, this one is really small to that.

I think you are confusing the final file size with the intermediate memory usage. Because of the way the LLC data are stored, you may need to download a large amount of data before you can subset it. 

I noticed you are using `k_chunksize=90`. This means that you are downloading all 90 vertical levels, then subsetting the top 5. Try instead with `k_chunksize=5` or even k_chunksize=``.

**Comment by rabernat** [comment]
I can confirm it works for me if you change `k_chunksize=90` to ` k_levels=[0, 1, 2, 3, 4]`.

**Comment by LemingVan** [comment]
Hi @rabernat, thank you for your help, I think the problem is solved.

**Comment by dhruvbalwada** [comment]
I have a further question on this front. It seems that for me things work when k_levels is small in number (like around 10) or k_chunksize is not too small (fails if this value is 1 or 2).  I tried k_levels=range(0,56) and that also failed. Things fail at the get_dataset step itself. 
Any idea why?

**Comment by rabernat** [comment]
Can you post the full error and traceback for "things failed"?

**Comment by dhruvbalwada** [comment]
there is no error, the kernel just crashes/restarts. (I am using pangeo google cloud - large size)
