### ISSUE TITLE
xmitgcm.open_mdsdataset cannot  read other variables, like 'uVeltave', 'Ttave' and so on

### ISSUE THREAD

**Issue by liu-ran** [MITgcm/xmitgcm#244]
When I use the xmitgcm.open_mdsdataset, I find it can only read the basic variables, like 'T', 'S', 'U', 'Eta'. But any other diagnostic outputs from MITgcm can't be read through the  xmitgcm.open_mdsdataset.

**Comment by rabernat** [comment]
Hi @liu-ran and thanks for your message. Xmitgcm can read nearly any file output by mitgcm. See documentation: https://xmitgcm.readthedocs.io/en/latest/usage.html#expected-files
It has a long [built-in](https://github.com/MITgcm/xmitgcm/blob/master/xmitgcm/variables.py#L311) list of variables, and it also can parse `availabile_diagnostics.log` to determine the meaning of diagnostic variables. It can definitely read the "tave" output.

If you are having problems, you will need to post a more specific issue, including the code you are using to read your data, a listing of the files in your data directory, and any error messages.

**Comment by rabernat** [comment]
Hi @liu-ran  - did you resolve this problem?

**Comment by liu-ran** [comment]
@rabernat Hi, I'm sorry for the reply so late. This problem is not resolved but I succeed to use the `rdmds` function to read the data. Specificly, as the picture shows,  the `xmitgcm` doesn't seem to read the prefix `PHIHYD` although the `PHIHYD` is in the available diagnostics.
![微信图片_20210112142423](https://user-images.githubusercontent.com/48266323/104277782-7065e480-54e2-11eb-8114-bfe3c959a115.png)

**Comment by liu-ran** [comment]
Also, my `xmitgcm` fail to read all iters due to the lack of the attribute 'auto_combine'. ( my `xarray` version is 0.16.1). But It is not a big problem. I can splice all iters manually.

![微信图片_20210112143448](https://user-images.githubusercontent.com/48266323/104278329-642e5700-54e3-11eb-8110-ab06699880d0.png)

**Comment by rabernat** [comment]
Just just need to upgrate xmitgcm to the latest version and all of these problems will be fixed.

Do you know how to upgrade? If you are using conda, you just run

```
conda update -c conda-forge xmitgcm
```

or pip

```
pip install --upgrade xmitgcm
```

**Comment by liu-ran** [comment]
@rabernat Wonderful! Many thanks!
