### ISSUE TITLE
How to get the data of LLC4320?

### ISSUE THREAD

**Issue by zhouchichi** [MITgcm/xmitgcm#274]
I use the code to get the data of LLC4320.
```
from xmitgcm import llcreader
model = llcreader.ECCOPortalLLC4320Model()
ds = model.get_dataset(varnames=['Theta'], k_levels=[0], type='latlon')
print(ds)
```
The result shows that:
```
<xarray.Dataset>
Dimensions:  (face: 13, i: 17280, i_g: 17280, j: 12960, j_g: 12960, k: 1, k_l: 1, k_p1: 2, k_u: 1, time: 10312)
Coordinates: (12/41)
  * face     (face) int32 0 1 2 3 4 5 6 7 8 9 10 11 12
  * i        (i) int32 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * i_g      (i_g) int32 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * j        (j) int32 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * j_g      (j_g) int32 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * k        (k) int32 0
    ...       ...
    XG       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YG       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxV      (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyU      (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Zl       (k_l) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zu       (k_u) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
Data variables:
    Theta    (time, k, j, i) float32 dask.array<chunksize=(1, 1, 12960, 4320), meta=np.ndarray>
```
The questions are:
1. Does the result show I make a success? I want to get the statistics and what is the next step? I don't know what to do.
2. What is the meaning of  "k_levels=[0]"? How to set it up correctly?

Thank you for any help.

**Comment by zhouchichi** [comment]
I have known how to solve it.

**Comment by zhouchichi** [comment]
I have known how to solve it.

**Comment by rabernat** [comment]
Hi @zhouchichi. Thanks for your message

1. Did you solve your problem? If so, could you please post the solution and "close" the issue?
2. Is this the same as #275?

**Comment by zhouchichi** [comment]
> Hi @zhouchichi. Thanks for your message
> 
> 1. Did you solve your problem? If so, could you please post the solution and "close" the issue?
> 2. Is this the same as [How to read data from a single file in LLC4320 ? #275](https://github.com/MITgcm/xmitgcm/issues/275)?

Thank you for your reply!
I will try to close it. I failed yesterday.
They are not the same. In #275, I want to read data from a single shrunk file instead of the whole LLC4320.  Can you help me? Thank you for any help!
