### ISSUE TITLE
dropping XC YC XG YG

### ISSUE THREAD

**Issue by mmazloff** [MITgcm/xmitgcm#276]
Hello,

Hope I am not just being dumb here, but lately I have had issues where when I open binary with open_mdsdataset it doesn't properly assign XC YC XG YG. 
In these cases ds = ds.sel(XC=slice(*lon_bnds)) leads to:
KeyError: 'no index found for coordinate XC'

This happens most often when there are many iters and I set iters='all', however even for those cases when I set a specific iter number and then it appears XC YC are present, such that ds = ds.sel(XC=slice(*lon_bnds)) does work, when I write to_netcdf XC and YC are not written. Instead only i and j indices are written. 

So, I am wondering if there is something new in the latest xmitgcm where one has to specify reading of all grid components? 

Thanks for any help!

**Comment by rabernat** [comment]
Hmmm, nothing was supposed to change, but just to be safe, can you upgrade to 0.5.2. That contained some bug fixes (e.g. #265, which is related).

Also, can you make sure you are using `read_grid=True, grid_vars_to_coords=True` in your call to `open_mdsdataset`?

**Comment by mmazloff** [comment]
I update all my packages, which included
  xmitgcm                                0.5.0-pyhd3deb0d_1 --> 0.5.2-pyhd8ed1ab_0
Now things are working! 
I suspect some packages were out of sync...sorry for bugging the list. Rookie mistake! 

I'll note that I did add: read_grid=True, grid_vars_to_coords=True
but that doesn't seem necessary as the problem went away with the update. 

Thanks Ryan! I'll close this now
