### ISSUE TITLE
Variable dimension typo?

### ISSUE THREAD

**Issue by LizzWebb** [MITgcm/xmitgcm#284]
Hi, 

I believe there is a typo, but I am unsure if it leads to any particular issues. Posting here just in case. 

When using llcreader for ecco model 2160, drF dimensions and size have an empty dimension. Please see the below block of code:
```
model = llcreader.ECCOPortalLLC2160Model()
ds_SIvel  = model.get_dataset(varnames=['SIuice','SIvice'], k_levels=[0])
print('drF    : ', ds_SIvel.drF.dims, '=', ds_SIvel.drF.shape)   
```
This outputs: 
`drF    :  ('k',) = (1,)`

Is this a typo, or am I importing this variable incorrectly?

Thank you!

**Comment by rabernat** [comment]
Thanks for the feedback @LizzWebb and welcome to the xmitgcm forum! 😄 

When you ask for `k_levels=[0]`, you are getting just a single vertical level of the model. The fact that
```
drF.dims == ('k',)
```
is telling you that the `drF` variable (cell thinkness) has dimension `k`, and the fact that
```
drF.shape == (1,)
```
is telling you that this variable has only one value (associated with the vertical level k 0). So your output looks right to me.

Could you say more about what you were expecting instead?

**Comment by LizzWebb** [comment]
Thanks for the quick feedback @rabernat !

I was surprised there was the additional comma; t makes me think there should be an additional dimension there. Is this an incorrect assumption?

Thank you!

**Comment by rabernat** [comment]
In python, `(1)` is just `1`.  Parentheses in this context don't do anything. You can verify this for yourself
```python
assert 1 == (1)
```
In contrast, `(1,)` is a [tuple](https://www.w3schools.com/python/python_tuples.asp).  The shapes of arrays are always expressed as tuples. So in this case, you can interpret the shape as "a 1D array with 1 element." Does that make sense?

**Comment by LizzWebb** [comment]
Yes, it does. Thank you for clarifying!
