### ISSUE TITLE
Assertion Error when .load() or .plot()

### ISSUE THREAD

**Issue by LizzWebb** [MITgcm/xmitgcm#291]
Hi all, 

I am trying to load and/or plot data from the llc4320 model; I have a script that has done this many times in the past but it recently stopped working, and now gives the message: 
Assertion Error: 

The lines I used are below: 
```
model = llcreader.ECCOPortalLLC4320Model()
ds_Ovel  = model.get_dataset(varnames=['U','V'], k_levels=[0])
OceUvel = ds_Ovel.U.isel(time=0,face=5, k=0)
OceUvel.load()
```

Does anyone know what is causing this, or if there is an update I missed? 
Thank you in advance!

**Comment by rabernat** [comment]
Hi @LizzWebb! Sorry for the friction. Could you post the full stack trace from your error? (Like all of the lines that python spits out above `AssertionError`.) That will help us narrow down the problem.

**Comment by rabernat** [comment]
FYI, as of right now, it looks like the ECCO data portal is down.

https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_4320/compressed/0000010368

![image](https://user-images.githubusercontent.com/1197350/143917970-4b7f310b-b3ce-449f-a035-406876dc14c4.png)

I suspect this is the root of the problem.

**Comment by LizzWebb** [comment]
Ah, my mistake. The ecco portal previously posted on their homepage when they were down. I didn't think to check the individual data sets. 

Thanks, @rabernat. I will wait for the data set to come back, and post the full error if it is not resolved.
