### ISSUE TITLE
LLC 4320 and LLC 2160 Configuration

### ISSUE THREAD

**Issue by LizzWebb** [MITgcm/xmitgcm#300]
Hi all, 

Is there documentation for the LLC 4320 and LLC 2160 models? I am specifically interested in the equations and values used to calculate the sea ice dynamics. Is it the same as ECCO V4?

Thank you in advance! 
Lizz

**Comment by rabernat** [comment]
You can find the configuration for all the runs here: https://github.com/MITgcm-contrib/llc_hires/

If the information you seek is not there, you should probably contact Dimitris Menemenlis.
