### ISSUE TITLE
ClientResponseError with llcreader

### ISSUE THREAD

**Issue by Shirui-peng** [MITgcm/xmitgcm#301]
Hello,

I have been using llcreader for a while, yet encounter a ClientResponseError for the first time today when running my usual code. The script is like
`model = llcreader.ECCOPortalLLC2160Model()`
`ds = model.get_dataset(varnames=['Salt', 'Theta'],
                       k_levels=[1],
                       iter_start=92160+80*24*6*30,iter_step=80*24*6)`
`print(ds.Theta[0,0,7,696,1348].values)`

And this now raises: ClientResponseError: 503, message='Service Unavailable', url=URL('https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000437760/Theta.0000437760.data.shrunk')

Thank you for the help.

**Comment by rabernat** [comment]
The ECCO portal is down

https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000437760/Theta.0000437760.data.shrunk

<img width="908" alt="image" src="https://user-images.githubusercontent.com/1197350/160492580-0a3dea7a-84c1-4f39-8f55-3aed0cdb6a25.png">


This happens pretty often. There is nothing we (xmitgcm devs) can do it about it. But feel free to complain to NAS: dataportal@nas.nasa.gov.
