### ISSUE TITLE
Cannot seek streaming HTTP file with llcreader

### ISSUE THREAD

**Issue by Shirui-peng** [MITgcm/xmitgcm#302]
Hello,

Thanks for pointing out the ECCO portal issue last week. I've been noticed by NAS currently that the filesystem is back up again. And I'm trying to run the same script as below:
`model = llcreader.ECCOPortalLLC2160Model()`
`ds = model.get_dataset(varnames=['Salt', 'Theta'], k_levels=[1], iter_start=92160+80*24*6*30,iter_step=80*24*6)`
`print(ds.Theta[0,0,7,696,1348].values)`

And this now raises: ValueError: Cannot seek streaming HTTP file.

Thank you again for the help.

**Comment by rabernat** [comment]
Can you report what version of fsspec you have?

```python
import fsspec
print(fsspec.__version__)
```

If you have an [old version](https://github.com/fsspec/filesystem_spec/tags) I will suggest you upgrade fsspec.

**Comment by Shirui-peng** [comment]
Thanks for the help. The version I have is 2021.09.0. I will try upgrading fsspec.

**Comment by Shirui-peng** [comment]
I have upgrade fsspec to version 2022.3.0, but still get the same error.

**Comment by rabernat** [comment]
It looks like the ECCO portal has stopped returning the [Content-Length header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length)

```
$ curl -I "https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000092160/Theta.0000092160.data.shrunk"
HTTP/1.1 200 OK
Date: Mon, 04 Apr 2022 23:12:25 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000
Pragma: no-cache
Expires: 0
Cache-Control: no-cache, no-store, must-revalidate
Content-Disposition: attachment; filename="Theta.0000092160.data.shrunk"
Content-Transfer-Encoding: binary
Accept-Ranges: bytes
Last-Modified: Thu, 24 Mar 2022 23:10:12 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/octet-stream
```

I believe this has caused all of our ECCO data portal stuff to break. It is not possible for fsspec to slice into files without knowing their size.

A related issue is that HTTP range requests seem to be broken as well

```
 curl -r 0-199  "https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_2160/compressed/0000092160/Theta.0000092160.data.shrunk" > testdata
```

This should just download 200 bytes of data. Instead it downloads the entire (huge file).

I will report this problem to NASA.

**Comment by rabernat** [comment]
NASA just got back to me with the following info

> I believe I found the source of the issue and corrected it. The cause of the problem came from a recent update we made to all the portals on the website. With the outage we experienced recently, the bug wasn’t encountered until the data became available for use again so I wasn’t immediately aware of an issue. When you have a chance, could you give it a try and see if everything is fine on your end?

All my checks show that things are working. @Shirui-peng if you confirm, we can close the issue.

**Comment by Shirui-peng** [comment]
Thank you for the update. I confirm that things are working for me as well.
