### ISSUE TITLE
LLC4320 Plotting Sea Surface Anomaly Issues

### ISSUE THREAD

**Issue by LizzWebb** [MITgcm/xmitgcm#314]
Hi all, 

I am using the LLC4320 data and I am planning to use the sea surface anomaly (eta) in the Arctic region. I have plotted it as a snapshot and monthly/seasonal averages, but it looks odd. Specifically, in all cases it seems to be showing linear kinematic features that are associated with the sea ice thickness. Is anyone able to explain why this is happening?

Below are the lines of code I have used for plotting a single snapshot for both eta and ice thickness. 

Thanks for any input! 

```
model = llcreader.ECCOPortalLLC4320Model()
ds       = model.get_dataset(varnames=['Eta', 'SIheff'])
ds.Eta.isel(face=6, time=0).plot.pcolormesh()
ds.SIheff.isel(face=6, time=0).plot.pcolormesh()
```

**Comment by timothyas** [comment]
Hey @LizzWebb, I am currently getting a `ClientResponseError` so I'm unable to look at the exact fields you are and I'm also no sea ice expert. However, my understanding is that `Eta` represents the ocean sea level anomaly (which can easily be scaled to a pressure anomaly) underneath the ice. So, it makes sense to me that we would see the imprint of sea ice thickness in the region. Could you paste in an image and indicate what features are unexpected? 

cc @mjlosch, sea ice aficianado

**Comment by mjlosch** [comment]
@LizzWebb I am not that familiar with the details of the llc4320 simulations, but in the default setup 
http://wwwcvs.mitgcm.org/viewvc/MITgcm/MITgcm_contrib/llc_hires/llc_4320/input/data?revision=1.15&view=markup
the combination of nonlinear free surface and "useRealFreshWaterFlux" means that the sea ice is 'immersed', i.e. it actually floats in the water obeying Archimedes' principle, and does not "levitate" on the water. To get the type of sea surface eta that you probably expect, you'd have to add the ice + snow contribution, probably something like (rhoIce*HEFF + rhoSnow *HSNOW)/rhoConst).
