### ISSUE TITLE
FSTimeoutError when trying to find desired lon/lat

### ISSUE THREAD

**Issue by auroralin0408** [MITgcm/xmitgcm#315]
I'm trying to choose desired lon/lat region in llc4320, using code:  
`model = llcreader.ECCOPortalLLC4320Model()`
`k_lv = list(np.arange(30))`
`ds = model.get_dataset(k_levels =k_lv, type='latlon')`
`iic,jjc = np.where((ds.XC>9)&(ds.XC<12)&(ds.YC>67.75)&(ds.YC<68.5))`

but it raised timeouterror... is it because the data is too large ??
Thanks for any answers :)

**Comment by timothyas** [comment]
Hi @auroralin0408! 👋 There is a chance that the server is down, this happens occasionally. However, you could also reduce the computation time by first selecting the LLC tiles that this logical statement covers. It looks like this is all on face 2, so maybe running `ds = ds.sel(face=2)` before the where command would help things out?

**Comment by timothyas** [comment]
Also, many numpy operations will act lazily on dask arrays but it seems like `np.where` is not one of them. So I would recommend to instead use [xarray's where function](https://docs.xarray.dev/en/stable/generated/xarray.where.html), so that it can apply the operation lazily on your dataset.

**Comment by auroralin0408** [comment]
Thanks for your quick reply! @timothyas 
I thought when I set `type='latlon`, there is no need to choose a certain tile as the variables don't have 'face' coordinate. And it seems that I can `model.get_dataset(face=2,k_levels =k_lv, type='latlon')` to reduce the computation at the beginning. I would try this later as the llc4320 data are temporarily unavailable.

And I will try to use xarray.where, thanks again!

**Comment by timothyas** [comment]
Great! Sorry, I somehow missed that you were using the latlon option. 

Would you mind reporting back whether or not this fixes your error once the server is up?

**Comment by auroralin0408** [comment]
Of course yes! 
And if I use the face option, does the  `ds.XC` still represent longitudes?

**Comment by timothyas** [comment]
Thanks! Yes XC will always represent longitude and YC latitude, they will just not necessarily be regularly spaced for certain parts of the globe. Check out [Forget et al, 2015](https://www.geosci-model-dev.net/8/3071/2015/) section 2 for some description of the grid. A lot of what is described is the LLC90 (1 degree) version, but everything except the grid spacing and telescoping at the equator pertains to LLC4320 (1/48).

**Comment by auroralin0408** [comment]
I've fixed my error, and I'll read that paper. Thanks a lot for your help!!

**Comment by timothyas** [comment]
No problem! I'm glad that worked.
