### ISSUE TITLE
open_mdsdataset() in directory with PH, PHL

### ISSUE THREAD

**Issue by IvanaEscobar** [MITgcm/xmitgcm#320]
I was trying to load binary data from `MITgcm/verification/tutorial_baroclinic_gyre` modifying a bit to generate data as binary instead of netcdf (ie. `V.0000000010.*ta` instead of `state.t*.nc`). Link to [verification doc](https://mitgcm.readthedocs.io/en/latest/examples/baroclinic_gyre/baroclinic_gyre.html#phi-hyd-discussion). Running the most simple call from the tutorial's top directory:
```
>>> import xmitgcm
>>> xmitgcm.open_mdsdataset('run/')
```

results in an error:
```
Traceback (most recent call last):
  File "/home/ivana/xmitgcm/xmitgcm/mds_store.py", line 202, in open_mdsdataset
    iternum = int(iters)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivana/xmitgcm/xmitgcm/mds_store.py", line 218, in open_mdsdataset
    raise IOError("Could not find the expected file "
OSError: Could not find the expected file prefixes ['T', 'W', 'Eta', 'S', 'V', 'U'] at iternum 1. (Instead found ['PHL', 'T', 'W', 'Eta', 'S', 'PH', 'V', 'U'])
```

The issue arises because `PH` and `PHL` are solved for after the first iteration, so they do not exist as part of `first_prefixes`. The work around I found was to specify `prefixes` in the function call. 

I was wondering if there was a way to ignore `PH` and `PHL`?

**Comment by IvanaEscobar** [comment]
Another hack is to add `PH` `PHL` at the zero-th iteration in your directory:
```
cp PH.0000000001.data PH.0000000000.data
cp PH.0000000001.meta PH.0000000000.meta
cp PHL.0000000001.data PHL.0000000000.data
cp PHL.0000000001.meta PHL.0000000000.meta
```

Don't recommend this approach in case you forget you've done this

**Comment by timothyas** [comment]
Hey @IvanaEscobar! You could use either the `prefixes` or the `iters` options to narrow down what you want. e.g. `xmitgcm.open_mdsdataset('run/', prefixes=["U", "V", "T", "S])` or `xmitgcm.open_mdsdataset('run/', iters=0)` ... or something like that.

I hope that helps. Also, if you don't want the initial state dumped you could set `dumpInitAndLast=.FALSE.` in `data` (see [here](https://mitgcm.readthedocs.io/en/latest/getting_started/getting_started.html#frequency-amount-of-output)).

**Comment by IvanaEscobar** [comment]
@timothyas thanks, I didn't think of the `iters` approach! Adding it to my notes.

This issue falls into the case when a user may not know which data is needed in postprocess and wants to do some first pass poking around (including initial state fields). 

I'll close the issue with a pin for myself to come back to implement different a `time` dimension for fields that don't span the full number of time steps provided by `dumpFreq` in the `data` runtime parameters of MITgcm.
