### ISSUE TITLE
Read model time output

### ISSUE THREAD

**Issue by mkyoungs** [MITgcm/xmitgcm#80]
In my meta files I see this parameter
timeInterval = [  3.153559200000E+07  6.307202000000E+07 ];
that we are currently not uploading.  Instead we set the time based on the input time step, but it would be useful to just be able to read the meta file instead of having to put in the timestep.  I would be happy to work on this, but I am a bit of a python noob and need some help.  Can anyone help me with this?

**Comment by edoddridge** [comment]
I don't see that information in all `*.meta` files, just the ones from pkg/diagnostics. Are your `*.meta` files exclusively generated by pkg/diagnostics?

E.g. this is what I get in a `Eta.*.meta` file:
```
 nDims = [   2 ];
 dimList = [
    60,    1,   30,
    60,    1,   30
 ];
 dataprec = [ 'float32' ];
 nrecords = [     1 ];
 timeStepNumber = [         10 ];
```

**Comment by mkyoungs** [comment]
I have output not from pkg/diagnostics such as `Eta.*.meta`, but I only use the data from pkg/diagnostics for analysis.

**Comment by rabernat** [comment]
@mkyoungs thanks for your feedback and suggestion.

I see how it would be convenient to automatically get the time from the meta files. On the other hand, this would introduce several potential complications such as:
- how to turn `timeInterval` into a specific time? (interval indexes are not supported by xarray yet)
- what is the "reference date" for the time if inferred from .meta files?
- which .meta file should be used if there are multiple files being read?
- what if there is a conflict between different .meta files?
- what if there is a conflict between the time inferred from the .meta file and the one suggested by `delta_t`?

Addressing and properly testing for all of these [edge cases](https://en.wikipedia.org/wiki/Edge_case) sounds like a significant amount of work. And for what benefit? For the convenience of not having to specify `delta_t=2400` when calling `open_mfdataset`? In terms of cost / benefit, it doesn't feel like the best use of my time to work on this feature.

However, if it is very important to you, you are welcome to work on it and submit a PR. The first step would be to check out the way `time` is currently set:
https://github.com/xgcm/xmitgcm/blob/master/xmitgcm/mds_store.py#L797-L809
and the way .meta files are parsed:
https://github.com/xgcm/xmitgcm/blob/master/xmitgcm/utils.py#L64-L82

Let us know if you have any questions along the way!

**Comment by aulemahal** [comment]
Hi, to get a time coordinate without specifying "delta_t" , couldn't we also try to read the "data" file and retrieve deltaTClock or deltaT?

**Comment by raphaeldussin** [comment]
Hi @aulemahal,

You can get deltaT from data with a function like this: 

```python
def find_dt():
    for line in open("data"):
        if 'deltaT' in line:
            # assuming one occurence of deltaT, else needs to pick one from list
            dt= line.replace(',','').split()[-1]
    return dt
```

**Comment by aulemahal** [comment]
Thanks, @raphaeldussin, it is indeed quite simple. But my question was also whether there is any reason that xmitgcm doesn't read the 'data' file? I mean, it could also infer the geometry from the flags, or store some of the configuration in the dataset's attributes. I could suggest such a PR, I just wondered if this was a deliberate choice not to implement it.

**Comment by rabernat** [comment]
Some reasons why we chose not to rely on the data file:
- data file is not always kept together with the data
- data file can be inconsistent with the data (e.g. if parameters are changed after the run is performed)
- parsing the data file is hard

That said, we would definitely be open to a PR which could help extract relevant information from the data file, as long as it was optional to use the feature.
